const VALIDATION_CONSTANTS = {
  COMPLAINT_CATEGORIES: ['Water', 'Road', 'Electricity', 'Sanitation', 'Other'],
  COMPLAINT_STATUSES: ['Submitted', 'In Progress', 'Resolved'],
  COMPLAINT_PRIORITIES: ['Low', 'Medium', 'High', 'Critical'],
  DESCRIPTION_MIN_LENGTH: 10,
  DESCRIPTION_MAX_LENGTH: 1000,
  LOCATION_MIN_LENGTH: 3,
  LOCATION_MAX_LENGTH: 255,
  IMAGE_BASE64_MAX_LENGTH: 700000,
  REMARK_MAX_LENGTH: 2000,
  ESCALATION_REASON_MAX_LENGTH: 500,
  PROOF_URL_MAX_LENGTH: 2048
};

module.exports = VALIDATION_CONSTANTS;
